version: 2.1

jobs:
  build-and-test:  
    machine: 
      image: ubuntu-2204:2024.01.2
      docker_layer_caching: true
    steps:
      - checkout
      - run: 
          name: Instalacja zależności
          command: make deps
      - run: 
          name: Uruchomienie testów
          command: make test
      - run:
          name: Sprawdzenie lintera
          command: make lint
      - run: make docker_build

workflows:
  basic:  
    jobs:
      - build-and-test
